# Site settings
title: VoIPDown.com
email: allo@voipdown.com
description: >
  Ce projet communautaire open source a été créé en réaction au blocage des technologies VoIP
  au Maroc par l'Agence Nationale de Réglementation des Télécommunications
  depuis le 5 Janvier 2016.
baseurl: ""
url: "http://voipdown.com"
fixedNav: 'true' # true or false
theme: orange # green, blue, orange, purple, grey
twitterUsername:
githubUsername: 'VoIPDown/voipdown.github.io'
facebookUsername:


# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md, raw, no-commit, scripts]
sass:
  style: compressed
